/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlayerStatisticsDto {
  imageUrl?: string | null;
  kd?: number;
  lastMatchPoints?: number;
  name?: string | null;
  place?: number;
  playerId?: string;
  totalLooses?: number;
  totalMatches?: number;
  totalWins?: number;
}
