/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UiHeroDto } from '../models/ui-hero-dto';
import { UiPlayerDto } from '../models/ui-player-dto';
export interface UiFighterDto {
  actionsMade?: number | null;
  cardsLeft?: number | null;
  hero?: UiHeroDto;
  heroId?: string;
  heroImageUrl?: string | null;
  hpLeft?: number | null;
  id?: string;
  isWinner?: boolean;
  itemsUsed?: number | null;
  matchId?: string;
  matchPoints?: number | null;
  player?: UiPlayerDto;
  playerId?: string;
  playerImageUrl?: string | null;
  sidekickHpLeft?: number | null;
  sidekickName?: string | null;
  timeSpentInSeconds?: number | null;
  turn?: number | null;
}
