/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UiPlayStyleDto } from '../models/ui-play-style-dto';
import { UiSidekickDto } from '../models/ui-sidekick-dto';
export interface UiHeroDto {
  color?: string | null;
  deckSize?: number;
  hp?: number;
  id?: string;
  imageUrl?: string | null;
  isRanged?: boolean;
  meleeRangeImageUrl?: string | null;
  name?: string | null;
  playStyle?: UiPlayStyleDto;
  sidekicks?: Array<UiSidekickDto> | null;
}
