/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UiPlayStyleDto {
  attack?: number;
  defence?: number;
  difficulty?: number;
  heroId?: string;
  id?: string;
  trickery?: number;
}
