/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UiSidekickDto {
  count?: number;
  hp?: number;
  id?: string;
  isRanged?: boolean;
  meleeRangeImageUrl?: string | null;
  name?: string | null;
}
