/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UiHeroDto } from '../../models/ui-hero-dto';

export interface ApiHeroesGet$Params {
}

export function apiHeroesGet(http: HttpClient, rootUrl: string, params?: ApiHeroesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UiHeroDto>>> {
  const rb = new RequestBuilder(rootUrl, apiHeroesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UiHeroDto>>;
    })
  );
}

apiHeroesGet.PATH = '/api/Heroes';
