/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UiHeroStatisticsDto } from '../../models/ui-hero-statistics-dto';

export interface ApiHeroesStatisticsGet$Params {
}

export function apiHeroesStatisticsGet(http: HttpClient, rootUrl: string, params?: ApiHeroesStatisticsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UiHeroStatisticsDto>>> {
  const rb = new RequestBuilder(rootUrl, apiHeroesStatisticsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UiHeroStatisticsDto>>;
    })
  );
}

apiHeroesStatisticsGet.PATH = '/api/Heroes/statistics';
