/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UiHeroStatisticsDto } from '../../models/ui-hero-statistics-dto';

export interface ApiHeroesStatisticsHeroIdGet$Params {
  heroId: string;
}

export function apiHeroesStatisticsHeroIdGet(http: HttpClient, rootUrl: string, params: ApiHeroesStatisticsHeroIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UiHeroStatisticsDto>> {
  const rb = new RequestBuilder(rootUrl, apiHeroesStatisticsHeroIdGet.PATH, 'get');
  if (params) {
    rb.path('heroId', params.heroId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UiHeroStatisticsDto>;
    })
  );
}

apiHeroesStatisticsHeroIdGet.PATH = '/api/Heroes/statistics/{heroId}';
