// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unmatched.CatalogService.EntityFramework.Context;

#nullable disable

namespace Unmatched.EntityFramework.Migrations
{
    [DbContext(typeof(UnmatchedDbContext))]
    partial class UnmatchedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Expansion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Expansions");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("ExpansionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpansionId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExpansionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpansionId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Minion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("ExpansionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpansionId");

                    b.ToTable("Minions");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.PlayStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Trickery")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("PlayStyles");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Sidekick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid?>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Sidekicks");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Villain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("ExpansionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpansionId");

                    b.ToTable("Villains");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Hero", b =>
                {
                    b.HasOne("Unmatched.CatalogService.Domain.Entities.Expansion", "Expansion")
                        .WithMany("Heroes")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Map", b =>
                {
                    b.HasOne("Unmatched.CatalogService.Domain.Entities.Expansion", "Expansion")
                        .WithMany("Maps")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Minion", b =>
                {
                    b.HasOne("Unmatched.CatalogService.Domain.Entities.Expansion", "Expansion")
                        .WithMany("Minions")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.PlayStyle", b =>
                {
                    b.HasOne("Unmatched.CatalogService.Domain.Entities.Hero", null)
                        .WithOne("PlayStyle")
                        .HasForeignKey("Unmatched.CatalogService.Domain.Entities.PlayStyle", "HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Sidekick", b =>
                {
                    b.HasOne("Unmatched.CatalogService.Domain.Entities.Hero", "Hero")
                        .WithMany("Sidekicks")
                        .HasForeignKey("HeroId");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Villain", b =>
                {
                    b.HasOne("Unmatched.CatalogService.Domain.Entities.Expansion", "Expansion")
                        .WithMany("Villains")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Expansion", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("Maps");

                    b.Navigation("Minions");

                    b.Navigation("Villains");
                });

            modelBuilder.Entity("Unmatched.CatalogService.Domain.Entities.Hero", b =>
                {
                    b.Navigation("PlayStyle");

                    b.Navigation("Sidekicks");
                });
#pragma warning restore 612, 618
        }
    }
}
