/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { HeroesService } from './services/heroes.service';
import { MatchesService } from './services/matches.service';
import { PlayersService } from './services/players.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    HeroesService,
    MatchesService,
    PlayersService,
    ApiConfiguration
  ],
})
export class BackendApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<BackendApiModule> {
    return {
      ngModule: BackendApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: BackendApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('BackendApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
