// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unmatched.MatchService.EntityFramework.Context;

#nullable disable

namespace Unmatched.MatchService.EntityFramework.Migrations
{
    [DbContext(typeof(UnmatchedDbContext))]
    [Migration("20260803134313_FixTournamentParticipantsMismatchDetection")]
    partial class FixTournamentParticipantsMismatchDetection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.FighterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActionsMade")
                        .HasColumnType("int");

                    b.Property<int?>("CardsLeft")
                        .HasColumnType("int");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HpLeft")
                        .HasColumnType("int");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemsUsed")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MatchPoints")
                        .HasColumnType("int");

                    b.Property<int?>("Placement")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SidekickHpLeft")
                        .HasColumnType("int");

                    b.Property<int?>("Team")
                        .HasColumnType("int");

                    b.Property<int?>("TimeSpentInSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("Turn")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.HeroTitleEntity", b =>
                {
                    b.Property<Guid>("HeroesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TitlesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Metric")
                        .HasColumnType("float");

                    b.Property<int>("TimesEarned")
                        .HasColumnType("int");

                    b.HasKey("HeroesId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("HeroTitle", (string)null);
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Epic")
                        .HasColumnType("int");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .HasColumnType("int");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchMinionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HpLeft")
                        .HasColumnType("int");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchVillainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchVillainId");

                    b.ToTable("MatchMinions");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchVillainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CardsLeft")
                        .HasColumnType("int");

                    b.Property<int?>("HpLeft")
                        .HasColumnType("int");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VillainId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchVillains");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.RatingRecalculationStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRecalculationRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RatingRecalculationState");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Exclusivity")
                        .HasColumnType("int");

                    b.Property<int?>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RuleKey")
                        .IsUnique()
                        .HasFilter("[RuleKey] IS NOT NULL");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TournamentAwardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AwardKind")
                        .HasColumnType("int");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "HeroId", "AwardKind")
                        .IsUnique()
                        .HasFilter("([AwardKind] <> 11)");

                    b.ToTable("TournamentAwards");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TournamentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int>("FinalFormat")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialStage")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StartingChampionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrophyImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TournamentParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FinalPlacement")
                        .HasColumnType("int");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "HeroId")
                        .IsUnique();

                    b.ToTable("TournamentParticipants");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TournamentTitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Kind")
                        .IsUnique();

                    b.ToTable("TournamentTitles");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.FighterEntity", b =>
                {
                    b.HasOne("Unmatched.MatchService.Domain.Entities.MatchEntity", "Match")
                        .WithMany("Fighters")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.HeroTitleEntity", b =>
                {
                    b.HasOne("Unmatched.MatchService.Domain.Entities.TitleEntity", null)
                        .WithMany("HeroTitles")
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchEntity", b =>
                {
                    b.HasOne("Unmatched.MatchService.Domain.Entities.TournamentEntity", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchMinionEntity", b =>
                {
                    b.HasOne("Unmatched.MatchService.Domain.Entities.MatchVillainEntity", null)
                        .WithMany("Minions")
                        .HasForeignKey("MatchVillainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchVillainEntity", b =>
                {
                    b.HasOne("Unmatched.MatchService.Domain.Entities.MatchEntity", null)
                        .WithOne("Villain")
                        .HasForeignKey("Unmatched.MatchService.Domain.Entities.MatchVillainEntity", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TournamentParticipantEntity", b =>
                {
                    b.HasOne("Unmatched.MatchService.Domain.Entities.TournamentEntity", null)
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TournamentTitleEntity", b =>
                {
                    b.HasOne("Unmatched.MatchService.Domain.Entities.TournamentEntity", null)
                        .WithMany("TournamentTitles")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchEntity", b =>
                {
                    b.Navigation("Fighters");

                    b.Navigation("Villain");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.MatchVillainEntity", b =>
                {
                    b.Navigation("Minions");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TitleEntity", b =>
                {
                    b.Navigation("HeroTitles");
                });

            modelBuilder.Entity("Unmatched.MatchService.Domain.Entities.TournamentEntity", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Participants");

                    b.Navigation("TournamentTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
