/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UiMatchLogDto } from '../../models/ui-match-log-dto';

export interface ApiMatchesHeroIdGet$Params {
  heroId: string;
}

export function apiMatchesHeroIdGet(http: HttpClient, rootUrl: string, params: ApiMatchesHeroIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UiMatchLogDto>>> {
  const rb = new RequestBuilder(rootUrl, apiMatchesHeroIdGet.PATH, 'get');
  if (params) {
    rb.path('heroId', params.heroId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UiMatchLogDto>>;
    })
  );
}

apiMatchesHeroIdGet.PATH = '/api/Matches/{heroId}';
