/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlayerStatisticsDto } from '../../models/player-statistics-dto';

export interface ApiPlayersStatisticsHeroIdGet$Params {
  heroId: string;
}

export function apiPlayersStatisticsHeroIdGet(http: HttpClient, rootUrl: string, params: ApiPlayersStatisticsHeroIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PlayerStatisticsDto>> {
  const rb = new RequestBuilder(rootUrl, apiPlayersStatisticsHeroIdGet.PATH, 'get');
  if (params) {
    rb.path('heroId', params.heroId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlayerStatisticsDto>;
    })
  );
}

apiPlayersStatisticsHeroIdGet.PATH = '/api/Players/statistics/{heroId}';
